package flavor.pie.sunkcost

import org.bukkit.Material
import org.spongepowered.api.block.BlockType
import org.spongepowered.api.item.ItemType
import org.spongepowered.api.item.ItemTypes

//fun Material.toItemType(): ItemType? = when (this) {
//    Material.ACACIA_DOOR -> ItemTypes.ACACIA_DOOR
//    Material.ACACIA_DOOR_ITEM -> ItemTypes.ACACIA_DOOR
//    Material.ACACIA_FENCE -> ItemTypes.ACACIA_FENCE
//    Material.ACACIA_FENCE_GATE -> ItemTypes.ACACIA_FENCE_GATE
//    Material.ACACIA_STAIRS -> ItemTypes.ACACIA_STAIRS
//    Material.ACTIVATOR_RAIL -> ItemTypes.ACTIVATOR_RAIL
//    Material.AIR -> ItemTypes.AIR
//    Material.ANVIL -> ItemTypes.ANVIL
//    Material.APPLE -> ItemTypes.APPLE
//    Material.ARMOR_STAND -> ItemTypes.ARMOR_STAND
//    Material.ARROW -> ItemTypes.ARROW
//    Material.BAKED_POTATO -> ItemTypes.BAKED_POTATO
//    Material.BANNER -> ItemTypes.BANNER
//    Material.BARRIER -> ItemTypes.BARRIER
//    Material.BEACON -> ItemTypes.BEACON
//    Material.BED -> ItemTypes.BED
//    Material.BEDROCK -> ItemTypes.BEDROCK
//    Material.BED_BLOCK -> ItemTypes.BED
//    Material.BEETROOT -> ItemTypes.BEETROOT
//    Material.BEETROOT_BLOCK -> null
//    Material.BEETROOT_SEEDS -> null
//    Material.BEETROOT_SOUP -> null
//    Material.BIRCH_DOOR -> null
//    Material.BIRCH_DOOR_ITEM -> null
//    Material.BIRCH_FENCE -> null
//    Material.BIRCH_FENCE_GATE -> null
//    Material.BIRCH_WOOD_STAIRS -> null
//    Material.BLACK_GLAZED_TERRACOTTA -> null
//    Material.BLACK_SHULKER_BOX -> null
//    Material.BLAZE_POWDER -> null
//    Material.BLAZE_ROD -> null
//    Material.BLUE_GLAZED_TERRACOTTA -> null
//    Material.BLUE_SHULKER_BOX -> null
//    Material.BOAT -> null
//    Material.BOAT_ACACIA -> null
//    Material.BOAT_BIRCH -> null
//    Material.BOAT_DARK_OAK -> null
//    Material.BOAT_JUNGLE -> null
//    Material.BOAT_SPRUCE -> null
//    Material.BONE -> null
//    Material.BONE_BLOCK -> null
//    Material.BOOK -> null
//    Material.BOOKSHELF -> null
//    Material.BOOK_AND_QUILL -> null
//    Material.BOW -> null
//    Material.BOWL -> null
//    Material.BREAD -> null
//    Material.BREWING_STAND -> null
//    Material.BREWING_STAND_ITEM -> null
//    Material.BRICK -> null
//    Material.BRICK_STAIRS -> null
//    Material.BROWN_GLAZED_TERRACOTTA -> null
//    Material.BROWN_MUSHROOM -> null
//    Material.BROWN_SHULKER_BOX -> null
//    Material.BUCKET -> null
//    Material.BURNING_FURNACE -> null
//    Material.CACTUS -> null
//    Material.CAKE -> null
//    Material.CAKE_BLOCK -> null
//    Material.CARPET
//}

fun Material.toItemType(): ItemType? = when (this) {
    Material.AIR -> ItemTypes.AIR
    Material.STONE -> ItemTypes.STONE
    Material.GRASS -> ItemTypes.GRASS
    Material.DIRT -> ItemTypes.DIRT
    Material.COBBLESTONE -> ItemTypes.COBBLESTONE
    Material.WOOD -> ItemTypes.LOG
    Material.SAPLING -> ItemTypes.SAPLING
    Material.BEDROCK -> ItemTypes.BEDROCK
    Material.WATER -> null
    Material.STATIONARY_WATER -> null
    Material.LAVA -> null
    Material.STATIONARY_LAVA -> null
    Material.SAND -> ItemTypes.SAND
    Material.GRAVEL -> ItemTypes.GRAVEL
    Material.GOLD_ORE -> ItemTypes.GOLD_ORE
    Material.IRON_ORE -> ItemTypes.IRON_ORE
    Material.COAL_ORE -> ItemTypes.COAL_ORE
    Material.LOG -> ItemTypes.LOG
    Material.LEAVES -> ItemTypes.LEAVES
    Material.SPONGE -> ItemTypes.SPONGE
    Material.GLASS -> ItemTypes.GLASS
    Material.LAPIS_ORE -> ItemTypes.LAPIS_ORE
    Material.LAPIS_BLOCK -> ItemTypes.LAPIS_BLOCK
    Material.DISPENSER -> ItemTypes.DISPENSER
    Material.SANDSTONE -> ItemTypes.SANDSTONE
    Material.NOTE_BLOCK -> ItemTypes.NOTEBLOCK
    Material.BED_BLOCK -> ItemTypes.BED
    Material.POWERED_RAIL -> ItemTypes.GOLDEN_RAIL
    Material.DETECTOR_RAIL -> ItemTypes.DETECTOR_RAIL
    Material.PISTON_STICKY_BASE -> ItemTypes.STICKY_PISTON
    Material.WEB -> ItemTypes.WEB
    Material.LONG_GRASS -> ItemTypes.TALLGRASS
    Material.DEAD_BUSH -> ItemTypes.DEADBUSH
    Material.PISTON_BASE -> ItemTypes.PISTON
    Material.PISTON_EXTENSION -> ItemTypes.PISTON
    Material.WOOL -> ItemTypes.WOOL
    Material.PISTON_MOVING_PIECE -> ItemTypes.PISTON
    Material.YELLOW_FLOWER -> ItemTypes.YELLOW_FLOWER
    Material.RED_ROSE -> ItemTypes.RED_FLOWER
    Material.BROWN_MUSHROOM -> ItemTypes.BROWN_MUSHROOM
    Material.RED_MUSHROOM -> ItemTypes.RED_MUSHROOM
    Material.GOLD_BLOCK -> ItemTypes.GOLD_BLOCK
    Material.IRON_BLOCK -> ItemTypes.IRON_BLOCK
    Material.DOUBLE_STEP -> ItemTypes.STONE_SLAB
    Material.STEP -> ItemTypes.STONE_SLAB
    Material.BRICK -> ItemTypes.BRICK
    Material.TNT -> ItemTypes.TNT
    Material.BOOKSHELF -> ItemTypes.BOOKSHELF
    Material.MOSSY_COBBLESTONE -> ItemTypes.MOSSY_COBBLESTONE
    Material.OBSIDIAN -> ItemTypes.OBSIDIAN
    Material.TORCH -> ItemTypes.TORCH
    Material.FIRE -> null
    Material.MOB_SPAWNER -> ItemTypes.MOB_SPAWNER
    Material.WOOD_STAIRS -> ItemTypes.OAK_STAIRS
    Material.CHEST -> ItemTypes.CHEST
    Material.REDSTONE_WIRE -> ItemTypes.REDSTONE
    Material.DIAMOND_ORE -> ItemTypes.DIAMOND_ORE
    Material.DIAMOND_BLOCK -> ItemTypes.DIAMOND_BLOCK
    Material.WORKBENCH -> ItemTypes.CRAFTING_TABLE
    Material.CROPS -> ItemTypes.WHEAT_SEEDS
    Material.SOIL -> ItemTypes.FARMLAND
    Material.FURNACE -> ItemTypes.FURNACE
    Material.BURNING_FURNACE -> ItemTypes.FURNACE
    Material.SIGN_POST -> ItemTypes.SIGN
    Material.WOODEN_DOOR -> ItemTypes.WOODEN_DOOR
    Material.LADDER -> ItemTypes.LADDER
    Material.RAILS -> ItemTypes.RAIL
    Material.COBBLESTONE_STAIRS -> ItemTypes.STONE_STAIRS
    Material.WALL_SIGN -> ItemTypes.SIGN
    Material.LEVER -> ItemTypes.LEVER
    Material.STONE_PLATE -> ItemTypes.STONE_PRESSURE_PLATE
    Material.IRON_DOOR_BLOCK -> ItemTypes.IRON_DOOR
    Material.WOOD_PLATE -> ItemTypes.WOODEN_PRESSURE_PLATE
    Material.REDSTONE_ORE -> ItemTypes.REDSTONE_ORE
    Material.GLOWING_REDSTONE_ORE -> ItemTypes.REDSTONE_ORE
    Material.REDSTONE_TORCH_OFF -> ItemTypes.REDSTONE_TORCH
    Material.REDSTONE_TORCH_ON -> ItemTypes.REDSTONE_TORCH
    Material.STONE_BUTTON -> ItemTypes.STONE_BUTTON
    Material.SNOW -> ItemTypes.SNOW
    Material.ICE -> ItemTypes.ICE
    Material.SNOW_BLOCK -> ItemTypes.SNOW
    Material.CACTUS -> ItemTypes.CACTUS
    Material.CLAY -> ItemTypes.CLAY
    Material.SUGAR_CANE_BLOCK -> ItemTypes.REEDS
    Material.JUKEBOX -> ItemTypes.JUKEBOX
    Material.FENCE -> ItemTypes.FENCE
    Material.PUMPKIN -> ItemTypes.PUMPKIN
    Material.NETHERRACK -> ItemTypes.NETHERRACK
    Material.SOUL_SAND -> ItemTypes.SOUL_SAND
    Material.GLOWSTONE -> ItemTypes.GLOWSTONE
    Material.PORTAL -> null
    Material.JACK_O_LANTERN -> ItemTypes.LIT_PUMPKIN
    Material.CAKE_BLOCK -> ItemTypes.CAKE
    Material.DIODE_BLOCK_OFF -> ItemTypes.REPEATER
    Material.DIODE_BLOCK_ON -> ItemTypes.REPEATER
    Material.STAINED_GLASS -> ItemTypes.STAINED_GLASS
    Material.TRAP_DOOR -> ItemTypes.TRAPDOOR
    Material.MONSTER_EGGS -> ItemTypes.MONSTER_EGG
    Material.SMOOTH_BRICK -> ItemTypes.STONEBRICK
    Material.HUGE_MUSHROOM_1 -> ItemTypes.BROWN_MUSHROOM_BLOCK
    Material.HUGE_MUSHROOM_2 -> ItemTypes.RED_MUSHROOM_BLOCK
    Material.IRON_FENCE -> ItemTypes.IRON_BARS
    Material.THIN_GLASS -> ItemTypes.GLASS_PANE
    Material.MELON_BLOCK -> ItemTypes.MELON_BLOCK
    Material.PUMPKIN_STEM -> ItemTypes.PUMPKIN_SEEDS
    Material.MELON_STEM -> ItemTypes.MELON_SEEDS
    Material.VINE -> ItemTypes.VINE
    Material.FENCE_GATE -> ItemTypes.FENCE_GATE
    Material.BRICK_STAIRS -> ItemTypes.BRICK_STAIRS
    Material.SMOOTH_STAIRS -> ItemTypes.STONE_BRICK_STAIRS
    Material.MYCEL -> ItemTypes.MYCELIUM
    Material.WATER_LILY -> ItemTypes.WATERLILY
    Material.NETHER_BRICK -> ItemTypes.NETHER_BRICK
    Material.NETHER_FENCE -> ItemTypes.NETHER_BRICK_FENCE
    Material.NETHER_BRICK_STAIRS -> ItemTypes.NETHER_BRICK_STAIRS
    Material.NETHER_WARTS -> ItemTypes.NETHER_WART
    Material.ENCHANTMENT_TABLE -> ItemTypes.ENCHANTING_TABLE
    Material.BREWING_STAND -> ItemTypes.BREWING_STAND
    Material.CAULDRON -> ItemTypes.CAULDRON
    Material.ENDER_PORTAL -> null
    Material.ENDER_PORTAL_FRAME -> ItemTypes.END_PORTAL_FRAME
    Material.ENDER_STONE -> ItemTypes.END_STONE
    Material.DRAGON_EGG -> ItemTypes.DRAGON_EGG
    Material.REDSTONE_LAMP_OFF -> ItemTypes.REDSTONE_LAMP
    Material.REDSTONE_LAMP_ON -> ItemTypes.REDSTONE_LAMP
    Material.WOOD_DOUBLE_STEP -> ItemTypes.WOODEN_SLAB
    Material.WOOD_STEP -> ItemTypes.OAK_STAIRS
    Material.COCOA -> ItemTypes.DYE
    Material.SANDSTONE_STAIRS -> ItemTypes.SANDSTONE_STAIRS
    Material.EMERALD_ORE -> ItemTypes.EMERALD_ORE
    Material.ENDER_CHEST -> ItemTypes.ENDER_CHEST
    Material.TRIPWIRE_HOOK -> ItemTypes.TRIPWIRE_HOOK
    Material.TRIPWIRE -> ItemTypes.STRING
    Material.EMERALD_BLOCK -> ItemTypes.EMERALD_BLOCK
    Material.SPRUCE_WOOD_STAIRS -> ItemTypes.SPRUCE_STAIRS
    Material.BIRCH_WOOD_STAIRS -> ItemTypes.BIRCH_STAIRS
    Material.JUNGLE_WOOD_STAIRS -> ItemTypes.JUNGLE_STAIRS
    Material.COMMAND -> ItemTypes.COMMAND_BLOCK
    Material.BEACON -> ItemTypes.BEACON
    Material.COBBLE_WALL -> ItemTypes.COBBLESTONE_WALL
    Material.FLOWER_POT -> ItemTypes.FLOWER_POT
    Material.CARROT -> ItemTypes.CARROT
    Material.POTATO -> ItemTypes.POTATO
    Material.WOOD_BUTTON -> ItemTypes.WOODEN_BUTTON
    Material.SKULL -> ItemTypes.SKULL
    Material.ANVIL -> ItemTypes.ANVIL
    Material.TRAPPED_CHEST -> ItemTypes.TRAPPED_CHEST
    Material.GOLD_PLATE -> ItemTypes.LIGHT_WEIGHTED_PRESSURE_PLATE
    Material.IRON_PLATE -> ItemTypes.HEAVY_WEIGHTED_PRESSURE_PLATE
    Material.REDSTONE_COMPARATOR_OFF -> ItemTypes.COMPARATOR
    Material.REDSTONE_COMPARATOR_ON -> ItemTypes.COMPARATOR
    Material.DAYLIGHT_DETECTOR -> ItemTypes.DAYLIGHT_DETECTOR
    Material.REDSTONE_BLOCK -> ItemTypes.REDSTONE_BLOCK
    Material.QUARTZ_ORE -> ItemTypes.QUARTZ_ORE
    Material.HOPPER -> ItemTypes.HOPPER
    Material.QUARTZ_BLOCK -> ItemTypes.QUARTZ_BLOCK
    Material.QUARTZ_STAIRS -> ItemTypes.QUARTZ_STAIRS
    Material.ACTIVATOR_RAIL -> ItemTypes.ACTIVATOR_RAIL
    Material.DROPPER -> ItemTypes.DROPPER
    Material.STAINED_CLAY -> ItemTypes.STAINED_HARDENED_CLAY
    Material.STAINED_GLASS_PANE -> ItemTypes.STAINED_GLASS_PANE
    Material.LEAVES_2 -> ItemTypes.LEAVES2
    Material.LOG_2 -> ItemTypes.LOG2
    Material.ACACIA_STAIRS -> ItemTypes.ACACIA_STAIRS
    Material.DARK_OAK_STAIRS -> ItemTypes.DARK_OAK_STAIRS
    Material.SLIME_BLOCK -> ItemTypes.SLIME
    Material.BARRIER -> ItemTypes.BARRIER
    Material.IRON_TRAPDOOR -> ItemTypes.IRON_TRAPDOOR
    Material.PRISMARINE -> ItemTypes.PRISMARINE
    Material.SEA_LANTERN -> ItemTypes.SEA_LANTERN
    Material.HAY_BLOCK -> ItemTypes.HAY_BLOCK
    Material.CARPET -> ItemTypes.CARPET
    Material.HARD_CLAY -> ItemTypes.HARDENED_CLAY
    Material.COAL_BLOCK -> ItemTypes.COAL_BLOCK
    Material.PACKED_ICE -> ItemTypes.PACKED_ICE
    Material.DOUBLE_PLANT -> ItemTypes.DOUBLE_PLANT
    Material.STANDING_BANNER -> ItemTypes.BANNER
    Material.WALL_BANNER -> ItemTypes.BANNER
    Material.DAYLIGHT_DETECTOR_INVERTED -> ItemTypes.DAYLIGHT_DETECTOR
    Material.RED_SANDSTONE -> ItemTypes.RED_SANDSTONE
    Material.RED_SANDSTONE_STAIRS -> ItemTypes.RED_SANDSTONE_STAIRS
    Material.DOUBLE_STONE_SLAB2 -> ItemTypes.STONE_SLAB2
    Material.STONE_SLAB2 -> ItemTypes.STONE_SLAB2
    Material.SPRUCE_FENCE_GATE -> ItemTypes.SPRUCE_FENCE_GATE
    Material.BIRCH_FENCE_GATE -> ItemTypes.BIRCH_FENCE_GATE
    Material.JUNGLE_FENCE_GATE -> ItemTypes.JUNGLE_FENCE_GATE
    Material.DARK_OAK_FENCE_GATE -> ItemTypes.DARK_OAK_FENCE_GATE
    Material.ACACIA_FENCE_GATE -> ItemTypes.ACACIA_FENCE_GATE
    Material.SPRUCE_FENCE -> ItemTypes.SPRUCE_FENCE
    Material.BIRCH_FENCE -> ItemTypes.BIRCH_FENCE
    Material.JUNGLE_FENCE -> ItemTypes.JUNGLE_FENCE
    Material.DARK_OAK_FENCE -> ItemTypes.DARK_OAK_FENCE
    Material.ACACIA_FENCE -> ItemTypes.ACACIA_FENCE
    Material.SPRUCE_DOOR -> ItemTypes.SPRUCE_DOOR
    Material.BIRCH_DOOR -> ItemTypes.BIRCH_DOOR
    Material.JUNGLE_DOOR -> ItemTypes.JUNGLE_DOOR
    Material.ACACIA_DOOR -> ItemTypes.ACACIA_DOOR
    Material.DARK_OAK_DOOR -> ItemTypes.DARK_OAK_DOOR
    Material.END_ROD -> ItemTypes.END_ROD
    Material.CHORUS_PLANT -> ItemTypes.CHORUS_PLANT
    Material.CHORUS_FLOWER -> ItemTypes.CHORUS_FLOWER
    Material.PURPUR_BLOCK -> ItemTypes.PURPUR_BLOCK
    Material.PURPUR_PILLAR -> ItemTypes.PURPUR_PILLAR
    Material.PURPUR_STAIRS -> ItemTypes.PURPUR_STAIRS
    Material.PURPUR_DOUBLE_SLAB -> ItemTypes.PURPUR_SLAB
    Material.PURPUR_SLAB -> ItemTypes.PURPUR_SLAB
    Material.END_BRICKS -> ItemTypes.END_BRICKS
    Material.BEETROOT_BLOCK -> ItemTypes.BEETROOT
    Material.GRASS_PATH -> ItemTypes.GRASS_PATH
    Material.END_GATEWAY -> null
    Material.COMMAND_REPEATING -> ItemTypes.REPEATING_COMMAND_BLOCK
    Material.COMMAND_CHAIN -> ItemTypes.CHAIN_COMMAND_BLOCK
    Material.FROSTED_ICE -> ItemTypes.PACKED_ICE
    Material.MAGMA -> ItemTypes.MAGMA
    Material.NETHER_WART_BLOCK -> ItemTypes.NETHER_WART_BLOCK
    Material.RED_NETHER_BRICK -> ItemTypes.RED_NETHER_BRICK
    Material.BONE_BLOCK -> ItemTypes.BONE_BLOCK
    Material.STRUCTURE_VOID -> ItemTypes.STRUCTURE_VOID
    Material.OBSERVER -> ItemTypes.OBSERVER
    Material.WHITE_SHULKER_BOX -> ItemTypes.WHITE_SHULKER_BOX
    Material.ORANGE_SHULKER_BOX -> ItemTypes.ORANGE_SHULKER_BOX
    Material.MAGENTA_SHULKER_BOX -> ItemTypes.MAGENTA_SHULKER_BOX
    Material.LIGHT_BLUE_SHULKER_BOX -> ItemTypes.LIGHT_BLUE_SHULKER_BOX
    Material.YELLOW_SHULKER_BOX -> ItemTypes.YELLOW_SHULKER_BOX
    Material.LIME_SHULKER_BOX -> ItemTypes.LIME_SHULKER_BOX
    Material.PINK_SHULKER_BOX -> ItemTypes.PINK_SHULKER_BOX
    Material.GRAY_SHULKER_BOX -> ItemTypes.GRAY_SHULKER_BOX
    Material.SILVER_SHULKER_BOX -> ItemTypes.SILVER_SHULKER_BOX
    Material.CYAN_SHULKER_BOX -> ItemTypes.CYAN_SHULKER_BOX
    Material.PURPLE_SHULKER_BOX -> ItemTypes.PURPLE_SHULKER_BOX
    Material.BLUE_SHULKER_BOX -> ItemTypes.BLUE_SHULKER_BOX
    Material.BROWN_SHULKER_BOX -> ItemTypes.BROWN_SHULKER_BOX
    Material.GREEN_SHULKER_BOX -> ItemTypes.GREEN_SHULKER_BOX
    Material.RED_SHULKER_BOX -> ItemTypes.RED_SHULKER_BOX
    Material.BLACK_SHULKER_BOX -> ItemTypes.BLACK_SHULKER_BOX
    Material.WHITE_GLAZED_TERRACOTTA -> ItemTypes.WHITE_GLAZED_TERRACOTTA
    Material.ORANGE_GLAZED_TERRACOTTA -> ItemTypes.ORANGE_GLAZED_TERRACOTTA
    Material.MAGENTA_GLAZED_TERRACOTTA -> ItemTypes.MAGENTA_GLAZED_TERRACOTTA
    Material.LIGHT_BLUE_GLAZED_TERRACOTTA -> ItemTypes.LIGHT_BLUE_GLAZED_TERRACOTTA
    Material.YELLOW_GLAZED_TERRACOTTA -> ItemTypes.YELLOW_GLAZED_TERRACOTTA
    Material.LIME_GLAZED_TERRACOTTA -> ItemTypes.LIME_GLAZED_TERRACOTTA
    Material.PINK_GLAZED_TERRACOTTA -> ItemTypes.PINK_GLAZED_TERRACOTTA
    Material.GRAY_GLAZED_TERRACOTTA -> ItemTypes.GRAY_GLAZED_TERRACOTTA
    Material.SILVER_GLAZED_TERRACOTTA -> ItemTypes.SILVER_GLAZED_TERRACOTTA
    Material.CYAN_GLAZED_TERRACOTTA -> ItemTypes.CYAN_GLAZED_TERRACOTTA
    Material.PURPLE_GLAZED_TERRACOTTA -> ItemTypes.PURPLE_GLAZED_TERRACOTTA
    Material.BLUE_GLAZED_TERRACOTTA -> ItemTypes.BLUE_GLAZED_TERRACOTTA
    Material.BROWN_GLAZED_TERRACOTTA -> ItemTypes.BROWN_GLAZED_TERRACOTTA
    Material.GREEN_GLAZED_TERRACOTTA -> ItemTypes.GREEN_GLAZED_TERRACOTTA
    Material.RED_GLAZED_TERRACOTTA -> ItemTypes.RED_GLAZED_TERRACOTTA
    Material.BLACK_GLAZED_TERRACOTTA -> ItemTypes.BLACK_GLAZED_TERRACOTTA
    Material.CONCRETE -> ItemTypes.CONCRETE
    Material.CONCRETE_POWDER -> ItemTypes.CONCRETE_POWDER
    Material.STRUCTURE_BLOCK -> ItemTypes.STRUCTURE_BLOCK
    Material.IRON_SPADE -> ItemTypes.IRON_SHOVEL
    Material.IRON_PICKAXE -> ItemTypes.IRON_PICKAXE
    Material.IRON_AXE -> ItemTypes.IRON_AXE
    Material.FLINT_AND_STEEL -> ItemTypes.FLINT_AND_STEEL
    Material.APPLE -> ItemTypes.APPLE
    Material.BOW -> ItemTypes.BOW
    Material.ARROW -> ItemTypes.ARROW
    Material.COAL -> ItemTypes.COAL
    Material.DIAMOND -> ItemTypes.DIAMOND
    Material.IRON_INGOT -> ItemTypes.IRON_INGOT
    Material.GOLD_INGOT -> ItemTypes.GOLD_INGOT
    Material.IRON_SWORD -> ItemTypes.IRON_SWORD
    Material.WOOD_SWORD -> ItemTypes.WOODEN_SWORD
    Material.WOOD_SPADE -> ItemTypes.WOODEN_SHOVEL
    Material.WOOD_PICKAXE -> ItemTypes.WOODEN_PICKAXE
    Material.WOOD_AXE -> ItemTypes.WOODEN_AXE
    Material.STONE_SWORD -> ItemTypes.STONE_SWORD
    Material.STONE_SPADE -> ItemTypes.STONE_SHOVEL
    Material.STONE_PICKAXE -> ItemTypes.STONE_PICKAXE
    Material.STONE_AXE -> ItemTypes.STONE_AXE
    Material.DIAMOND_SWORD -> ItemTypes.DIAMOND_SWORD
    Material.DIAMOND_SPADE -> ItemTypes.DIAMOND_SHOVEL
    Material.DIAMOND_PICKAXE -> ItemTypes.DIAMOND_PICKAXE
    Material.DIAMOND_AXE -> ItemTypes.DIAMOND_AXE
    Material.STICK -> ItemTypes.STICK
    Material.BOWL -> ItemTypes.BOWL
    Material.MUSHROOM_SOUP -> ItemTypes.MUSHROOM_STEW
    Material.GOLD_SWORD -> ItemTypes.GOLDEN_SWORD
    Material.GOLD_SPADE -> ItemTypes.GOLDEN_SHOVEL
    Material.GOLD_PICKAXE -> ItemTypes.GOLDEN_PICKAXE
    Material.GOLD_AXE -> ItemTypes.GOLDEN_AXE
    Material.STRING -> ItemTypes.STRING
    Material.FEATHER -> ItemTypes.FEATHER
    Material.SULPHUR -> ItemTypes.GUNPOWDER
    Material.WOOD_HOE -> ItemTypes.WOODEN_HOE
    Material.STONE_HOE -> ItemTypes.STONE_HOE
    Material.IRON_HOE -> ItemTypes.IRON_HOE
    Material.DIAMOND_HOE -> ItemTypes.DIAMOND_HOE
    Material.GOLD_HOE -> ItemTypes.GOLDEN_HOE
    Material.SEEDS -> ItemTypes.WHEAT_SEEDS
    Material.WHEAT -> ItemTypes.WHEAT
    Material.BREAD -> ItemTypes.BREAD
    Material.LEATHER_HELMET -> ItemTypes.LEATHER_HELMET
    Material.LEATHER_CHESTPLATE -> ItemTypes.LEATHER_CHESTPLATE
    Material.LEATHER_LEGGINGS -> ItemTypes.LEATHER_LEGGINGS
    Material.LEATHER_BOOTS -> ItemTypes.LEATHER_BOOTS
    Material.CHAINMAIL_HELMET -> ItemTypes.CHAINMAIL_HELMET
    Material.CHAINMAIL_CHESTPLATE -> ItemTypes.CHAINMAIL_CHESTPLATE
    Material.CHAINMAIL_LEGGINGS -> ItemTypes.CHAINMAIL_LEGGINGS
    Material.CHAINMAIL_BOOTS -> ItemTypes.CHAINMAIL_BOOTS
    Material.IRON_HELMET -> ItemTypes.IRON_HELMET
    Material.IRON_CHESTPLATE -> ItemTypes.IRON_CHESTPLATE
    Material.IRON_LEGGINGS -> ItemTypes.IRON_LEGGINGS
    Material.IRON_BOOTS -> ItemTypes.IRON_BOOTS
    Material.DIAMOND_HELMET -> ItemTypes.DIAMOND_HELMET
    Material.DIAMOND_CHESTPLATE -> ItemTypes.DIAMOND_CHESTPLATE
    Material.DIAMOND_LEGGINGS -> ItemTypes.DIAMOND_LEGGINGS
    Material.DIAMOND_BOOTS -> ItemTypes.DIAMOND_BOOTS
    Material.GOLD_HELMET -> ItemTypes.GOLDEN_HELMET
    Material.GOLD_CHESTPLATE -> ItemTypes.GOLDEN_CHESTPLATE
    Material.GOLD_LEGGINGS -> ItemTypes.GOLDEN_LEGGINGS
    Material.GOLD_BOOTS -> ItemTypes.GOLDEN_BOOTS
    Material.FLINT -> ItemTypes.FLINT
    Material.PORK -> ItemTypes.PORKCHOP
    Material.GRILLED_PORK -> ItemTypes.COOKED_PORKCHOP
    Material.PAINTING -> ItemTypes.PAINTING
    Material.GOLDEN_APPLE -> ItemTypes.GOLDEN_APPLE
    Material.SIGN -> ItemTypes.SIGN
    Material.WOOD_DOOR -> ItemTypes.WOODEN_DOOR
    Material.BUCKET -> ItemTypes.BUCKET
    Material.WATER_BUCKET -> ItemTypes.WATER_BUCKET
    Material.LAVA_BUCKET -> ItemTypes.LAVA_BUCKET
    Material.MINECART -> ItemTypes.MINECART
    Material.SADDLE -> ItemTypes.SADDLE
    Material.IRON_DOOR -> ItemTypes.IRON_DOOR
    Material.REDSTONE -> ItemTypes.REDSTONE
    Material.SNOW_BALL -> ItemTypes.SNOWBALL
    Material.BOAT -> ItemTypes.BOAT
    Material.LEATHER -> ItemTypes.LEATHER
    Material.MILK_BUCKET -> ItemTypes.MILK_BUCKET
    Material.CLAY_BRICK -> ItemTypes.BRICK
    Material.CLAY_BALL -> ItemTypes.CLAY_BALL
    Material.SUGAR_CANE -> ItemTypes.REEDS
    Material.PAPER -> ItemTypes.PAPER
    Material.BOOK -> ItemTypes.BOOK
    Material.SLIME_BALL -> ItemTypes.SLIME_BALL
    Material.STORAGE_MINECART -> ItemTypes.CHEST_MINECART
    Material.POWERED_MINECART -> ItemTypes.FURNACE_MINECART
    Material.EGG -> ItemTypes.EGG
    Material.COMPASS -> ItemTypes.COMPASS
    Material.FISHING_ROD -> ItemTypes.FISHING_ROD
    Material.WATCH -> ItemTypes.CLOCK
    Material.GLOWSTONE_DUST -> ItemTypes.GLOWSTONE_DUST
    Material.RAW_FISH -> ItemTypes.FISH
    Material.COOKED_FISH -> ItemTypes.COOKED_FISH
    Material.INK_SACK -> ItemTypes.DYE
    Material.BONE -> ItemTypes.BONE
    Material.SUGAR -> ItemTypes.SUGAR
    Material.CAKE -> ItemTypes.CAKE
    Material.BED -> ItemTypes.BED
    Material.DIODE -> ItemTypes.REPEATER
    Material.COOKIE -> ItemTypes.COOKIE
    Material.MAP -> ItemTypes.MAP
    Material.SHEARS -> ItemTypes.SHEARS
    Material.MELON -> ItemTypes.MELON
    Material.PUMPKIN_SEEDS -> ItemTypes.PUMPKIN_SEEDS
    Material.MELON_SEEDS -> ItemTypes.MELON_SEEDS
    Material.RAW_BEEF -> ItemTypes.BEEF
    Material.COOKED_BEEF -> ItemTypes.COOKED_BEEF
    Material.RAW_CHICKEN -> ItemTypes.CHICKEN
    Material.COOKED_CHICKEN -> ItemTypes.COOKED_CHICKEN
    Material.ROTTEN_FLESH -> ItemTypes.ROTTEN_FLESH
    Material.ENDER_PEARL -> ItemTypes.ENDER_PEARL
    Material.BLAZE_ROD -> ItemTypes.BLAZE_ROD
    Material.GHAST_TEAR -> ItemTypes.GHAST_TEAR
    Material.GOLD_NUGGET -> ItemTypes.GOLD_NUGGET
    Material.NETHER_STALK -> ItemTypes.NETHER_WART
    Material.POTION -> ItemTypes.POTION
    Material.GLASS_BOTTLE -> ItemTypes.GLASS_BOTTLE
    Material.SPIDER_EYE -> ItemTypes.SPIDER_EYE
    Material.FERMENTED_SPIDER_EYE -> ItemTypes.FERMENTED_SPIDER_EYE
    Material.BLAZE_POWDER -> ItemTypes.BLAZE_POWDER
    Material.MAGMA_CREAM -> ItemTypes.MAGMA_CREAM
    Material.BREWING_STAND_ITEM -> ItemTypes.BREWING_STAND
    Material.CAULDRON_ITEM -> ItemTypes.CAULDRON
    Material.EYE_OF_ENDER -> ItemTypes.ENDER_EYE
    Material.SPECKLED_MELON -> ItemTypes.SPECKLED_MELON
    Material.MONSTER_EGG -> ItemTypes.MONSTER_EGG
    Material.EXP_BOTTLE -> ItemTypes.EXPERIENCE_BOTTLE
    Material.FIREBALL -> ItemTypes.FIRE_CHARGE
    Material.BOOK_AND_QUILL -> ItemTypes.WRITABLE_BOOK
    Material.WRITTEN_BOOK -> ItemTypes.WRITTEN_BOOK
    Material.EMERALD -> ItemTypes.EMERALD
    Material.ITEM_FRAME -> ItemTypes.ITEM_FRAME
    Material.FLOWER_POT_ITEM -> ItemTypes.FLOWER_POT
    Material.CARROT_ITEM -> ItemTypes.CARROT
    Material.POTATO_ITEM -> ItemTypes.POTATO
    Material.BAKED_POTATO -> ItemTypes.BAKED_POTATO
    Material.POISONOUS_POTATO -> ItemTypes.POISONOUS_POTATO
    Material.EMPTY_MAP -> ItemTypes.MAP
    Material.GOLDEN_CARROT -> ItemTypes.GOLDEN_CARROT
    Material.SKULL_ITEM -> ItemTypes.SKULL
    Material.CARROT_STICK -> ItemTypes.CARROT_ON_A_STICK
    Material.NETHER_STAR -> ItemTypes.NETHER_STAR
    Material.PUMPKIN_PIE -> ItemTypes.PUMPKIN_PIE
    Material.FIREWORK -> ItemTypes.FIREWORKS
    Material.FIREWORK_CHARGE -> ItemTypes.FIREWORK_CHARGE
    Material.ENCHANTED_BOOK -> ItemTypes.ENCHANTED_BOOK
    Material.REDSTONE_COMPARATOR -> ItemTypes.COMPARATOR
    Material.NETHER_BRICK_ITEM -> ItemTypes.NETHER_BRICK
    Material.QUARTZ -> ItemTypes.QUARTZ
    Material.EXPLOSIVE_MINECART -> ItemTypes.TNT_MINECART
    Material.HOPPER_MINECART -> ItemTypes.HOPPER_MINECART
    Material.PRISMARINE_SHARD -> ItemTypes.PRISMARINE_SHARD
    Material.PRISMARINE_CRYSTALS -> ItemTypes.PRISMARINE_CRYSTALS
    Material.RABBIT -> ItemTypes.RABBIT
    Material.COOKED_RABBIT -> ItemTypes.COOKED_RABBIT
    Material.RABBIT_STEW -> ItemTypes.RABBIT_STEW
    Material.RABBIT_FOOT -> ItemTypes.RABBIT_FOOT
    Material.RABBIT_HIDE -> ItemTypes.RABBIT_HIDE
    Material.ARMOR_STAND -> ItemTypes.ARMOR_STAND
    Material.IRON_BARDING -> ItemTypes.IRON_HORSE_ARMOR
    Material.GOLD_BARDING -> ItemTypes.GOLDEN_HORSE_ARMOR
    Material.DIAMOND_BARDING -> ItemTypes.DIAMOND_HORSE_ARMOR
    Material.LEASH -> ItemTypes.LEAD
    Material.NAME_TAG -> ItemTypes.NAME_TAG
    Material.COMMAND_MINECART -> ItemTypes.COMMAND_BLOCK_MINECART
    Material.MUTTON -> ItemTypes.MUTTON
    Material.COOKED_MUTTON -> ItemTypes.COOKED_MUTTON
    Material.BANNER -> ItemTypes.BANNER
    Material.END_CRYSTAL -> ItemTypes.END_CRYSTAL
    Material.SPRUCE_DOOR_ITEM -> ItemTypes.SPRUCE_DOOR
    Material.BIRCH_DOOR_ITEM -> ItemTypes.BIRCH_DOOR
    Material.JUNGLE_DOOR_ITEM -> ItemTypes.JUNGLE_DOOR
    Material.ACACIA_DOOR_ITEM -> ItemTypes.ACACIA_DOOR
    Material.DARK_OAK_DOOR_ITEM -> ItemTypes.DARK_OAK_DOOR
    Material.CHORUS_FRUIT -> ItemTypes.CHORUS_FRUIT
    Material.CHORUS_FRUIT_POPPED -> ItemTypes.CHORUS_FRUIT_POPPED
    Material.BEETROOT -> ItemTypes.BEETROOT
    Material.BEETROOT_SEEDS -> ItemTypes.BEETROOT_SEEDS
    Material.BEETROOT_SOUP -> ItemTypes.BEETROOT_SOUP
    Material.DRAGONS_BREATH -> ItemTypes.DRAGON_BREATH
    Material.SPLASH_POTION -> ItemTypes.SPLASH_POTION
    Material.SPECTRAL_ARROW -> ItemTypes.SPECTRAL_ARROW
    Material.TIPPED_ARROW -> ItemTypes.TIPPED_ARROW
    Material.LINGERING_POTION -> ItemTypes.LINGERING_POTION
    Material.SHIELD -> ItemTypes.SHIELD
    Material.ELYTRA -> ItemTypes.ELYTRA
    Material.BOAT_SPRUCE -> ItemTypes.SPRUCE_BOAT
    Material.BOAT_BIRCH -> ItemTypes.BIRCH_BOAT
    Material.BOAT_JUNGLE -> ItemTypes.JUNGLE_BOAT
    Material.BOAT_ACACIA -> ItemTypes.ACACIA_BOAT
    Material.BOAT_DARK_OAK -> ItemTypes.DARK_OAK_BOAT
    Material.TOTEM -> ItemTypes.TOTEM_OF_UNDYING
    Material.SHULKER_SHELL -> ItemTypes.SHULKER_SHELL
    Material.IRON_NUGGET -> ItemTypes.IRON_NUGGET
    Material.KNOWLEDGE_BOOK -> ItemTypes.KNOWLEDGE_BOOK
    Material.GOLD_RECORD -> ItemTypes.RECORD_13
    Material.GREEN_RECORD -> ItemTypes.RECORD_CAT
    Material.RECORD_3 -> ItemTypes.RECORD_BLOCKS
    Material.RECORD_4 -> ItemTypes.RECORD_CHIRP
    Material.RECORD_5 -> ItemTypes.RECORD_FAR
    Material.RECORD_6 -> ItemTypes.RECORD_MALL
    Material.RECORD_7 -> ItemTypes.RECORD_MELLOHI
    Material.RECORD_8 -> ItemTypes.RECORD_STAL
    Material.RECORD_9 -> ItemTypes.RECORD_STRAD
    Material.RECORD_10 -> ItemTypes.RECORD_WARD
    Material.RECORD_11 -> ItemTypes.RECORD_11
    Material.RECORD_12 -> ItemTypes.RECORD_WAIT
}

fun ItemType.toMaterial(): Material = when (this) {
    ItemTypes.AIR -> Material.AIR
    ItemTypes.STONE -> Material.STONE
    ItemTypes.GRASS -> Material.GRASS
    ItemTypes.DIRT -> Material.DIRT
    ItemTypes.COBBLESTONE -> Material.COBBLESTONE
    ItemTypes.LOG -> Material.WOOD
    ItemTypes.SAPLING -> Material.SAPLING
    ItemTypes.BEDROCK -> Material.BEDROCK
    ItemTypes.SAND -> Material.SAND
    ItemTypes.GRAVEL -> Material.GRAVEL
    ItemTypes.GOLD_ORE -> Material.GOLD_ORE
    ItemTypes.IRON_ORE -> Material.IRON_ORE
    ItemTypes.COAL_ORE -> Material.COAL_ORE
    ItemTypes.LOG -> Material.LOG
    ItemTypes.LEAVES -> Material.LEAVES
    ItemTypes.SPONGE -> Material.SPONGE
    ItemTypes.GLASS -> Material.GLASS
    ItemTypes.LAPIS_ORE -> Material.LAPIS_ORE
    ItemTypes.LAPIS_BLOCK -> Material.LAPIS_BLOCK
    ItemTypes.DISPENSER -> Material.DISPENSER
    ItemTypes.SANDSTONE -> Material.SANDSTONE
    ItemTypes.NOTEBLOCK -> Material.NOTE_BLOCK
    ItemTypes.BED -> Material.BED_BLOCK
    ItemTypes.GOLDEN_RAIL -> Material.POWERED_RAIL
    ItemTypes.DETECTOR_RAIL -> Material.DETECTOR_RAIL
    ItemTypes.STICKY_PISTON -> Material.PISTON_STICKY_BASE
    ItemTypes.WEB -> Material.WEB
    ItemTypes.TALLGRASS -> Material.LONG_GRASS
    ItemTypes.DEADBUSH -> Material.DEAD_BUSH
    ItemTypes.PISTON -> Material.PISTON_BASE
    ItemTypes.PISTON -> Material.PISTON_EXTENSION
    ItemTypes.WOOL -> Material.WOOL
    ItemTypes.PISTON -> Material.PISTON_MOVING_PIECE
    ItemTypes.YELLOW_FLOWER -> Material.YELLOW_FLOWER
    ItemTypes.RED_FLOWER -> Material.RED_ROSE
    ItemTypes.BROWN_MUSHROOM -> Material.BROWN_MUSHROOM
    ItemTypes.RED_MUSHROOM -> Material.RED_MUSHROOM
    ItemTypes.GOLD_BLOCK -> Material.GOLD_BLOCK
    ItemTypes.IRON_BLOCK -> Material.IRON_BLOCK
    ItemTypes.STONE_SLAB -> Material.DOUBLE_STEP
    ItemTypes.STONE_SLAB -> Material.STEP
    ItemTypes.BRICK -> Material.BRICK
    ItemTypes.TNT -> Material.TNT
    ItemTypes.BOOKSHELF -> Material.BOOKSHELF
    ItemTypes.MOSSY_COBBLESTONE -> Material.MOSSY_COBBLESTONE
    ItemTypes.OBSIDIAN -> Material.OBSIDIAN
    ItemTypes.TORCH -> Material.TORCH
    ItemTypes.MOB_SPAWNER -> Material.MOB_SPAWNER
    ItemTypes.OAK_STAIRS -> Material.WOOD_STAIRS
    ItemTypes.CHEST -> Material.CHEST
    ItemTypes.REDSTONE -> Material.REDSTONE_WIRE
    ItemTypes.DIAMOND_ORE -> Material.DIAMOND_ORE
    ItemTypes.DIAMOND_BLOCK -> Material.DIAMOND_BLOCK
    ItemTypes.CRAFTING_TABLE -> Material.WORKBENCH
    ItemTypes.WHEAT_SEEDS -> Material.CROPS
    ItemTypes.FARMLAND -> Material.SOIL
    ItemTypes.FURNACE -> Material.FURNACE
    ItemTypes.FURNACE -> Material.BURNING_FURNACE
    ItemTypes.SIGN -> Material.SIGN_POST
    ItemTypes.WOODEN_DOOR -> Material.WOODEN_DOOR
    ItemTypes.LADDER -> Material.LADDER
    ItemTypes.RAIL -> Material.RAILS
    ItemTypes.STONE_STAIRS -> Material.COBBLESTONE_STAIRS
    ItemTypes.SIGN -> Material.WALL_SIGN
    ItemTypes.LEVER -> Material.LEVER
    ItemTypes.STONE_PRESSURE_PLATE -> Material.STONE_PLATE
    ItemTypes.IRON_DOOR -> Material.IRON_DOOR_BLOCK
    ItemTypes.WOODEN_PRESSURE_PLATE -> Material.WOOD_PLATE
    ItemTypes.REDSTONE_ORE -> Material.REDSTONE_ORE
    ItemTypes.REDSTONE_ORE -> Material.GLOWING_REDSTONE_ORE
    ItemTypes.REDSTONE_TORCH -> Material.REDSTONE_TORCH_OFF
    ItemTypes.REDSTONE_TORCH -> Material.REDSTONE_TORCH_ON
    ItemTypes.STONE_BUTTON -> Material.STONE_BUTTON
    ItemTypes.SNOW -> Material.SNOW
    ItemTypes.ICE -> Material.ICE
    ItemTypes.SNOW -> Material.SNOW_BLOCK
    ItemTypes.CACTUS -> Material.CACTUS
    ItemTypes.CLAY -> Material.CLAY
    ItemTypes.REEDS -> Material.SUGAR_CANE_BLOCK
    ItemTypes.JUKEBOX -> Material.JUKEBOX
    ItemTypes.FENCE -> Material.FENCE
    ItemTypes.PUMPKIN -> Material.PUMPKIN
    ItemTypes.NETHERRACK -> Material.NETHERRACK
    ItemTypes.SOUL_SAND -> Material.SOUL_SAND
    ItemTypes.GLOWSTONE -> Material.GLOWSTONE
    ItemTypes.LIT_PUMPKIN -> Material.JACK_O_LANTERN
    ItemTypes.CAKE -> Material.CAKE_BLOCK
    ItemTypes.REPEATER -> Material.DIODE_BLOCK_OFF
    ItemTypes.REPEATER -> Material.DIODE_BLOCK_ON
    ItemTypes.STAINED_GLASS -> Material.STAINED_GLASS
    ItemTypes.TRAPDOOR -> Material.TRAP_DOOR
    ItemTypes.MONSTER_EGG -> Material.MONSTER_EGGS
    ItemTypes.STONEBRICK -> Material.SMOOTH_BRICK
    ItemTypes.BROWN_MUSHROOM_BLOCK -> Material.HUGE_MUSHROOM_1
    ItemTypes.RED_MUSHROOM_BLOCK -> Material.HUGE_MUSHROOM_2
    ItemTypes.IRON_BARS -> Material.IRON_FENCE
    ItemTypes.GLASS_PANE -> Material.THIN_GLASS
    ItemTypes.MELON_BLOCK -> Material.MELON_BLOCK
    ItemTypes.PUMPKIN_SEEDS -> Material.PUMPKIN_STEM
    ItemTypes.MELON_SEEDS -> Material.MELON_STEM
    ItemTypes.VINE -> Material.VINE
    ItemTypes.FENCE_GATE -> Material.FENCE_GATE
    ItemTypes.BRICK_STAIRS -> Material.BRICK_STAIRS
    ItemTypes.STONE_BRICK_STAIRS -> Material.SMOOTH_STAIRS
    ItemTypes.MYCELIUM -> Material.MYCEL
    ItemTypes.WATERLILY -> Material.WATER_LILY
    ItemTypes.NETHER_BRICK -> Material.NETHER_BRICK
    ItemTypes.NETHER_BRICK_FENCE -> Material.NETHER_FENCE
    ItemTypes.NETHER_BRICK_STAIRS -> Material.NETHER_BRICK_STAIRS
    ItemTypes.NETHER_WART -> Material.NETHER_WARTS
    ItemTypes.ENCHANTING_TABLE -> Material.ENCHANTMENT_TABLE
    ItemTypes.BREWING_STAND -> Material.BREWING_STAND
    ItemTypes.CAULDRON -> Material.CAULDRON
    ItemTypes.END_PORTAL_FRAME -> Material.ENDER_PORTAL_FRAME
    ItemTypes.END_STONE -> Material.ENDER_STONE
    ItemTypes.DRAGON_EGG -> Material.DRAGON_EGG
    ItemTypes.REDSTONE_LAMP -> Material.REDSTONE_LAMP_OFF
    ItemTypes.REDSTONE_LAMP -> Material.REDSTONE_LAMP_ON
    ItemTypes.WOODEN_SLAB -> Material.WOOD_DOUBLE_STEP
    ItemTypes.OAK_STAIRS -> Material.WOOD_STEP
    ItemTypes.DYE -> Material.COCOA
    ItemTypes.SANDSTONE_STAIRS -> Material.SANDSTONE_STAIRS
    ItemTypes.EMERALD_ORE -> Material.EMERALD_ORE
    ItemTypes.ENDER_CHEST -> Material.ENDER_CHEST
    ItemTypes.TRIPWIRE_HOOK -> Material.TRIPWIRE_HOOK
    ItemTypes.STRING -> Material.TRIPWIRE
    ItemTypes.EMERALD_BLOCK -> Material.EMERALD_BLOCK
    ItemTypes.SPRUCE_STAIRS -> Material.SPRUCE_WOOD_STAIRS
    ItemTypes.BIRCH_STAIRS -> Material.BIRCH_WOOD_STAIRS
    ItemTypes.JUNGLE_STAIRS -> Material.JUNGLE_WOOD_STAIRS
    ItemTypes.COMMAND_BLOCK -> Material.COMMAND
    ItemTypes.BEACON -> Material.BEACON
    ItemTypes.COBBLESTONE_WALL -> Material.COBBLE_WALL
    ItemTypes.FLOWER_POT -> Material.FLOWER_POT
    ItemTypes.CARROT -> Material.CARROT
    ItemTypes.POTATO -> Material.POTATO
    ItemTypes.WOODEN_BUTTON -> Material.WOOD_BUTTON
    ItemTypes.SKULL -> Material.SKULL
    ItemTypes.ANVIL -> Material.ANVIL
    ItemTypes.TRAPPED_CHEST -> Material.TRAPPED_CHEST
    ItemTypes.LIGHT_WEIGHTED_PRESSURE_PLATE -> Material.GOLD_PLATE
    ItemTypes.HEAVY_WEIGHTED_PRESSURE_PLATE -> Material.IRON_PLATE
    ItemTypes.COMPARATOR -> Material.REDSTONE_COMPARATOR_OFF
    ItemTypes.COMPARATOR -> Material.REDSTONE_COMPARATOR_ON
    ItemTypes.DAYLIGHT_DETECTOR -> Material.DAYLIGHT_DETECTOR
    ItemTypes.REDSTONE_BLOCK -> Material.REDSTONE_BLOCK
    ItemTypes.QUARTZ_ORE -> Material.QUARTZ_ORE
    ItemTypes.HOPPER -> Material.HOPPER
    ItemTypes.QUARTZ_BLOCK -> Material.QUARTZ_BLOCK
    ItemTypes.QUARTZ_STAIRS -> Material.QUARTZ_STAIRS
    ItemTypes.ACTIVATOR_RAIL -> Material.ACTIVATOR_RAIL
    ItemTypes.DROPPER -> Material.DROPPER
    ItemTypes.STAINED_HARDENED_CLAY -> Material.STAINED_CLAY
    ItemTypes.STAINED_GLASS_PANE -> Material.STAINED_GLASS_PANE
    ItemTypes.LEAVES2 -> Material.LEAVES_2
    ItemTypes.LOG2 -> Material.LOG_2
    ItemTypes.ACACIA_STAIRS -> Material.ACACIA_STAIRS
    ItemTypes.DARK_OAK_STAIRS -> Material.DARK_OAK_STAIRS
    ItemTypes.SLIME -> Material.SLIME_BLOCK
    ItemTypes.BARRIER -> Material.BARRIER
    ItemTypes.IRON_TRAPDOOR -> Material.IRON_TRAPDOOR
    ItemTypes.PRISMARINE -> Material.PRISMARINE
    ItemTypes.SEA_LANTERN -> Material.SEA_LANTERN
    ItemTypes.HAY_BLOCK -> Material.HAY_BLOCK
    ItemTypes.CARPET -> Material.CARPET
    ItemTypes.HARDENED_CLAY -> Material.HARD_CLAY
    ItemTypes.COAL_BLOCK -> Material.COAL_BLOCK
    ItemTypes.PACKED_ICE -> Material.PACKED_ICE
    ItemTypes.DOUBLE_PLANT -> Material.DOUBLE_PLANT
    ItemTypes.BANNER -> Material.STANDING_BANNER
    ItemTypes.BANNER -> Material.WALL_BANNER
    ItemTypes.DAYLIGHT_DETECTOR -> Material.DAYLIGHT_DETECTOR_INVERTED
    ItemTypes.RED_SANDSTONE -> Material.RED_SANDSTONE
    ItemTypes.RED_SANDSTONE_STAIRS -> Material.RED_SANDSTONE_STAIRS
    ItemTypes.STONE_SLAB2 -> Material.DOUBLE_STONE_SLAB2
    ItemTypes.STONE_SLAB2 -> Material.STONE_SLAB2
    ItemTypes.SPRUCE_FENCE_GATE -> Material.SPRUCE_FENCE_GATE
    ItemTypes.BIRCH_FENCE_GATE -> Material.BIRCH_FENCE_GATE
    ItemTypes.JUNGLE_FENCE_GATE -> Material.JUNGLE_FENCE_GATE
    ItemTypes.DARK_OAK_FENCE_GATE -> Material.DARK_OAK_FENCE_GATE
    ItemTypes.ACACIA_FENCE_GATE -> Material.ACACIA_FENCE_GATE
    ItemTypes.SPRUCE_FENCE -> Material.SPRUCE_FENCE
    ItemTypes.BIRCH_FENCE -> Material.BIRCH_FENCE
    ItemTypes.JUNGLE_FENCE -> Material.JUNGLE_FENCE
    ItemTypes.DARK_OAK_FENCE -> Material.DARK_OAK_FENCE
    ItemTypes.ACACIA_FENCE -> Material.ACACIA_FENCE
    ItemTypes.SPRUCE_DOOR -> Material.SPRUCE_DOOR
    ItemTypes.BIRCH_DOOR -> Material.BIRCH_DOOR
    ItemTypes.JUNGLE_DOOR -> Material.JUNGLE_DOOR
    ItemTypes.ACACIA_DOOR -> Material.ACACIA_DOOR
    ItemTypes.DARK_OAK_DOOR -> Material.DARK_OAK_DOOR
    ItemTypes.END_ROD -> Material.END_ROD
    ItemTypes.CHORUS_PLANT -> Material.CHORUS_PLANT
    ItemTypes.CHORUS_FLOWER -> Material.CHORUS_FLOWER
    ItemTypes.PURPUR_BLOCK -> Material.PURPUR_BLOCK
    ItemTypes.PURPUR_PILLAR -> Material.PURPUR_PILLAR
    ItemTypes.PURPUR_STAIRS -> Material.PURPUR_STAIRS
    ItemTypes.PURPUR_SLAB -> Material.PURPUR_DOUBLE_SLAB
    ItemTypes.PURPUR_SLAB -> Material.PURPUR_SLAB
    ItemTypes.END_BRICKS -> Material.END_BRICKS
    ItemTypes.BEETROOT -> Material.BEETROOT_BLOCK
    ItemTypes.GRASS_PATH -> Material.GRASS_PATH
    ItemTypes.REPEATING_COMMAND_BLOCK -> Material.COMMAND_REPEATING
    ItemTypes.CHAIN_COMMAND_BLOCK -> Material.COMMAND_CHAIN
    ItemTypes.PACKED_ICE -> Material.FROSTED_ICE
    ItemTypes.MAGMA -> Material.MAGMA
    ItemTypes.NETHER_WART_BLOCK -> Material.NETHER_WART_BLOCK
    ItemTypes.RED_NETHER_BRICK -> Material.RED_NETHER_BRICK
    ItemTypes.BONE_BLOCK -> Material.BONE_BLOCK
    ItemTypes.STRUCTURE_VOID -> Material.STRUCTURE_VOID
    ItemTypes.OBSERVER -> Material.OBSERVER
    ItemTypes.WHITE_SHULKER_BOX -> Material.WHITE_SHULKER_BOX
    ItemTypes.ORANGE_SHULKER_BOX -> Material.ORANGE_SHULKER_BOX
    ItemTypes.MAGENTA_SHULKER_BOX -> Material.MAGENTA_SHULKER_BOX
    ItemTypes.LIGHT_BLUE_SHULKER_BOX -> Material.LIGHT_BLUE_SHULKER_BOX
    ItemTypes.YELLOW_SHULKER_BOX -> Material.YELLOW_SHULKER_BOX
    ItemTypes.LIME_SHULKER_BOX -> Material.LIME_SHULKER_BOX
    ItemTypes.PINK_SHULKER_BOX -> Material.PINK_SHULKER_BOX
    ItemTypes.GRAY_SHULKER_BOX -> Material.GRAY_SHULKER_BOX
    ItemTypes.SILVER_SHULKER_BOX -> Material.SILVER_SHULKER_BOX
    ItemTypes.CYAN_SHULKER_BOX -> Material.CYAN_SHULKER_BOX
    ItemTypes.PURPLE_SHULKER_BOX -> Material.PURPLE_SHULKER_BOX
    ItemTypes.BLUE_SHULKER_BOX -> Material.BLUE_SHULKER_BOX
    ItemTypes.BROWN_SHULKER_BOX -> Material.BROWN_SHULKER_BOX
    ItemTypes.GREEN_SHULKER_BOX -> Material.GREEN_SHULKER_BOX
    ItemTypes.RED_SHULKER_BOX -> Material.RED_SHULKER_BOX
    ItemTypes.BLACK_SHULKER_BOX -> Material.BLACK_SHULKER_BOX
    ItemTypes.WHITE_GLAZED_TERRACOTTA -> Material.WHITE_GLAZED_TERRACOTTA
    ItemTypes.ORANGE_GLAZED_TERRACOTTA -> Material.ORANGE_GLAZED_TERRACOTTA
    ItemTypes.MAGENTA_GLAZED_TERRACOTTA -> Material.MAGENTA_GLAZED_TERRACOTTA
    ItemTypes.LIGHT_BLUE_GLAZED_TERRACOTTA -> Material.LIGHT_BLUE_GLAZED_TERRACOTTA
    ItemTypes.YELLOW_GLAZED_TERRACOTTA -> Material.YELLOW_GLAZED_TERRACOTTA
    ItemTypes.LIME_GLAZED_TERRACOTTA -> Material.LIME_GLAZED_TERRACOTTA
    ItemTypes.PINK_GLAZED_TERRACOTTA -> Material.PINK_GLAZED_TERRACOTTA
    ItemTypes.GRAY_GLAZED_TERRACOTTA -> Material.GRAY_GLAZED_TERRACOTTA
    ItemTypes.SILVER_GLAZED_TERRACOTTA -> Material.SILVER_GLAZED_TERRACOTTA
    ItemTypes.CYAN_GLAZED_TERRACOTTA -> Material.CYAN_GLAZED_TERRACOTTA
    ItemTypes.PURPLE_GLAZED_TERRACOTTA -> Material.PURPLE_GLAZED_TERRACOTTA
    ItemTypes.BLUE_GLAZED_TERRACOTTA -> Material.BLUE_GLAZED_TERRACOTTA
    ItemTypes.BROWN_GLAZED_TERRACOTTA -> Material.BROWN_GLAZED_TERRACOTTA
    ItemTypes.GREEN_GLAZED_TERRACOTTA -> Material.GREEN_GLAZED_TERRACOTTA
    ItemTypes.RED_GLAZED_TERRACOTTA -> Material.RED_GLAZED_TERRACOTTA
    ItemTypes.BLACK_GLAZED_TERRACOTTA -> Material.BLACK_GLAZED_TERRACOTTA
    ItemTypes.CONCRETE -> Material.CONCRETE
    ItemTypes.CONCRETE_POWDER -> Material.CONCRETE_POWDER
    ItemTypes.STRUCTURE_BLOCK -> Material.STRUCTURE_BLOCK
    ItemTypes.IRON_SHOVEL -> Material.IRON_SPADE
    ItemTypes.IRON_PICKAXE -> Material.IRON_PICKAXE
    ItemTypes.IRON_AXE -> Material.IRON_AXE
    ItemTypes.FLINT_AND_STEEL -> Material.FLINT_AND_STEEL
    ItemTypes.APPLE -> Material.APPLE
    ItemTypes.BOW -> Material.BOW
    ItemTypes.ARROW -> Material.ARROW
    ItemTypes.COAL -> Material.COAL
    ItemTypes.DIAMOND -> Material.DIAMOND
    ItemTypes.IRON_INGOT -> Material.IRON_INGOT
    ItemTypes.GOLD_INGOT -> Material.GOLD_INGOT
    ItemTypes.IRON_SWORD -> Material.IRON_SWORD
    ItemTypes.WOODEN_SWORD -> Material.WOOD_SWORD
    ItemTypes.WOODEN_SHOVEL -> Material.WOOD_SPADE
    ItemTypes.WOODEN_PICKAXE -> Material.WOOD_PICKAXE
    ItemTypes.WOODEN_AXE -> Material.WOOD_AXE
    ItemTypes.STONE_SWORD -> Material.STONE_SWORD
    ItemTypes.STONE_SHOVEL -> Material.STONE_SPADE
    ItemTypes.STONE_PICKAXE -> Material.STONE_PICKAXE
    ItemTypes.STONE_AXE -> Material.STONE_AXE
    ItemTypes.DIAMOND_SWORD -> Material.DIAMOND_SWORD
    ItemTypes.DIAMOND_SHOVEL -> Material.DIAMOND_SPADE
    ItemTypes.DIAMOND_PICKAXE -> Material.DIAMOND_PICKAXE
    ItemTypes.DIAMOND_AXE -> Material.DIAMOND_AXE
    ItemTypes.STICK -> Material.STICK
    ItemTypes.BOWL -> Material.BOWL
    ItemTypes.MUSHROOM_STEW -> Material.MUSHROOM_SOUP
    ItemTypes.GOLDEN_SWORD -> Material.GOLD_SWORD
    ItemTypes.GOLDEN_SHOVEL -> Material.GOLD_SPADE
    ItemTypes.GOLDEN_PICKAXE -> Material.GOLD_PICKAXE
    ItemTypes.GOLDEN_AXE -> Material.GOLD_AXE
    ItemTypes.STRING -> Material.STRING
    ItemTypes.FEATHER -> Material.FEATHER
    ItemTypes.GUNPOWDER -> Material.SULPHUR
    ItemTypes.WOODEN_HOE -> Material.WOOD_HOE
    ItemTypes.STONE_HOE -> Material.STONE_HOE
    ItemTypes.IRON_HOE -> Material.IRON_HOE
    ItemTypes.DIAMOND_HOE -> Material.DIAMOND_HOE
    ItemTypes.GOLDEN_HOE -> Material.GOLD_HOE
    ItemTypes.WHEAT_SEEDS -> Material.SEEDS
    ItemTypes.WHEAT -> Material.WHEAT
    ItemTypes.BREAD -> Material.BREAD
    ItemTypes.LEATHER_HELMET -> Material.LEATHER_HELMET
    ItemTypes.LEATHER_CHESTPLATE -> Material.LEATHER_CHESTPLATE
    ItemTypes.LEATHER_LEGGINGS -> Material.LEATHER_LEGGINGS
    ItemTypes.LEATHER_BOOTS -> Material.LEATHER_BOOTS
    ItemTypes.CHAINMAIL_HELMET -> Material.CHAINMAIL_HELMET
    ItemTypes.CHAINMAIL_CHESTPLATE -> Material.CHAINMAIL_CHESTPLATE
    ItemTypes.CHAINMAIL_LEGGINGS -> Material.CHAINMAIL_LEGGINGS
    ItemTypes.CHAINMAIL_BOOTS -> Material.CHAINMAIL_BOOTS
    ItemTypes.IRON_HELMET -> Material.IRON_HELMET
    ItemTypes.IRON_CHESTPLATE -> Material.IRON_CHESTPLATE
    ItemTypes.IRON_LEGGINGS -> Material.IRON_LEGGINGS
    ItemTypes.IRON_BOOTS -> Material.IRON_BOOTS
    ItemTypes.DIAMOND_HELMET -> Material.DIAMOND_HELMET
    ItemTypes.DIAMOND_CHESTPLATE -> Material.DIAMOND_CHESTPLATE
    ItemTypes.DIAMOND_LEGGINGS -> Material.DIAMOND_LEGGINGS
    ItemTypes.DIAMOND_BOOTS -> Material.DIAMOND_BOOTS
    ItemTypes.GOLDEN_HELMET -> Material.GOLD_HELMET
    ItemTypes.GOLDEN_CHESTPLATE -> Material.GOLD_CHESTPLATE
    ItemTypes.GOLDEN_LEGGINGS -> Material.GOLD_LEGGINGS
    ItemTypes.GOLDEN_BOOTS -> Material.GOLD_BOOTS
    ItemTypes.FLINT -> Material.FLINT
    ItemTypes.PORKCHOP -> Material.PORK
    ItemTypes.COOKED_PORKCHOP -> Material.GRILLED_PORK
    ItemTypes.PAINTING -> Material.PAINTING
    ItemTypes.GOLDEN_APPLE -> Material.GOLDEN_APPLE
    ItemTypes.SIGN -> Material.SIGN
    ItemTypes.WOODEN_DOOR -> Material.WOOD_DOOR
    ItemTypes.BUCKET -> Material.BUCKET
    ItemTypes.WATER_BUCKET -> Material.WATER_BUCKET
    ItemTypes.LAVA_BUCKET -> Material.LAVA_BUCKET
    ItemTypes.MINECART -> Material.MINECART
    ItemTypes.SADDLE -> Material.SADDLE
    ItemTypes.IRON_DOOR -> Material.IRON_DOOR
    ItemTypes.REDSTONE -> Material.REDSTONE
    ItemTypes.SNOWBALL -> Material.SNOW_BALL
    ItemTypes.BOAT -> Material.BOAT
    ItemTypes.LEATHER -> Material.LEATHER
    ItemTypes.MILK_BUCKET -> Material.MILK_BUCKET
    ItemTypes.BRICK -> Material.CLAY_BRICK
    ItemTypes.CLAY_BALL -> Material.CLAY_BALL
    ItemTypes.REEDS -> Material.SUGAR_CANE
    ItemTypes.PAPER -> Material.PAPER
    ItemTypes.BOOK -> Material.BOOK
    ItemTypes.SLIME_BALL -> Material.SLIME_BALL
    ItemTypes.CHEST_MINECART -> Material.STORAGE_MINECART
    ItemTypes.FURNACE_MINECART -> Material.POWERED_MINECART
    ItemTypes.EGG -> Material.EGG
    ItemTypes.COMPASS -> Material.COMPASS
    ItemTypes.FISHING_ROD -> Material.FISHING_ROD
    ItemTypes.CLOCK -> Material.WATCH
    ItemTypes.GLOWSTONE_DUST -> Material.GLOWSTONE_DUST
    ItemTypes.FISH -> Material.RAW_FISH
    ItemTypes.COOKED_FISH -> Material.COOKED_FISH
    ItemTypes.DYE -> Material.INK_SACK
    ItemTypes.BONE -> Material.BONE
    ItemTypes.SUGAR -> Material.SUGAR
    ItemTypes.CAKE -> Material.CAKE
    ItemTypes.BED -> Material.BED
    ItemTypes.REPEATER -> Material.DIODE
    ItemTypes.COOKIE -> Material.COOKIE
    ItemTypes.MAP -> Material.MAP
    ItemTypes.SHEARS -> Material.SHEARS
    ItemTypes.MELON -> Material.MELON
    ItemTypes.PUMPKIN_SEEDS -> Material.PUMPKIN_SEEDS
    ItemTypes.MELON_SEEDS -> Material.MELON_SEEDS
    ItemTypes.BEEF -> Material.RAW_BEEF
    ItemTypes.COOKED_BEEF -> Material.COOKED_BEEF
    ItemTypes.CHICKEN -> Material.RAW_CHICKEN
    ItemTypes.COOKED_CHICKEN -> Material.COOKED_CHICKEN
    ItemTypes.ROTTEN_FLESH -> Material.ROTTEN_FLESH
    ItemTypes.ENDER_PEARL -> Material.ENDER_PEARL
    ItemTypes.BLAZE_ROD -> Material.BLAZE_ROD
    ItemTypes.GHAST_TEAR -> Material.GHAST_TEAR
    ItemTypes.GOLD_NUGGET -> Material.GOLD_NUGGET
    ItemTypes.NETHER_WART -> Material.NETHER_STALK
    ItemTypes.POTION -> Material.POTION
    ItemTypes.GLASS_BOTTLE -> Material.GLASS_BOTTLE
    ItemTypes.SPIDER_EYE -> Material.SPIDER_EYE
    ItemTypes.FERMENTED_SPIDER_EYE -> Material.FERMENTED_SPIDER_EYE
    ItemTypes.BLAZE_POWDER -> Material.BLAZE_POWDER
    ItemTypes.MAGMA_CREAM -> Material.MAGMA_CREAM
    ItemTypes.BREWING_STAND -> Material.BREWING_STAND_ITEM
    ItemTypes.CAULDRON -> Material.CAULDRON_ITEM
    ItemTypes.ENDER_EYE -> Material.EYE_OF_ENDER
    ItemTypes.SPECKLED_MELON -> Material.SPECKLED_MELON
    ItemTypes.MONSTER_EGG -> Material.MONSTER_EGG
    ItemTypes.EXPERIENCE_BOTTLE -> Material.EXP_BOTTLE
    ItemTypes.FIRE_CHARGE -> Material.FIREBALL
    ItemTypes.WRITABLE_BOOK -> Material.BOOK_AND_QUILL
    ItemTypes.WRITTEN_BOOK -> Material.WRITTEN_BOOK
    ItemTypes.EMERALD -> Material.EMERALD
    ItemTypes.ITEM_FRAME -> Material.ITEM_FRAME
    ItemTypes.FLOWER_POT -> Material.FLOWER_POT_ITEM
    ItemTypes.CARROT -> Material.CARROT_ITEM
    ItemTypes.POTATO -> Material.POTATO_ITEM
    ItemTypes.BAKED_POTATO -> Material.BAKED_POTATO
    ItemTypes.POISONOUS_POTATO -> Material.POISONOUS_POTATO
    ItemTypes.MAP -> Material.EMPTY_MAP
    ItemTypes.GOLDEN_CARROT -> Material.GOLDEN_CARROT
    ItemTypes.SKULL -> Material.SKULL_ITEM
    ItemTypes.CARROT_ON_A_STICK -> Material.CARROT_STICK
    ItemTypes.NETHER_STAR -> Material.NETHER_STAR
    ItemTypes.PUMPKIN_PIE -> Material.PUMPKIN_PIE
    ItemTypes.FIREWORKS -> Material.FIREWORK
    ItemTypes.FIREWORK_CHARGE -> Material.FIREWORK_CHARGE
    ItemTypes.ENCHANTED_BOOK -> Material.ENCHANTED_BOOK
    ItemTypes.COMPARATOR -> Material.REDSTONE_COMPARATOR
    ItemTypes.NETHER_BRICK -> Material.NETHER_BRICK_ITEM
    ItemTypes.QUARTZ -> Material.QUARTZ
    ItemTypes.TNT_MINECART -> Material.EXPLOSIVE_MINECART
    ItemTypes.HOPPER_MINECART -> Material.HOPPER_MINECART
    ItemTypes.PRISMARINE_SHARD -> Material.PRISMARINE_SHARD
    ItemTypes.PRISMARINE_CRYSTALS -> Material.PRISMARINE_CRYSTALS
    ItemTypes.RABBIT -> Material.RABBIT
    ItemTypes.COOKED_RABBIT -> Material.COOKED_RABBIT
    ItemTypes.RABBIT_STEW -> Material.RABBIT_STEW
    ItemTypes.RABBIT_FOOT -> Material.RABBIT_FOOT
    ItemTypes.RABBIT_HIDE -> Material.RABBIT_HIDE
    ItemTypes.ARMOR_STAND -> Material.ARMOR_STAND
    ItemTypes.IRON_HORSE_ARMOR -> Material.IRON_BARDING
    ItemTypes.GOLDEN_HORSE_ARMOR -> Material.GOLD_BARDING
    ItemTypes.DIAMOND_HORSE_ARMOR -> Material.DIAMOND_BARDING
    ItemTypes.LEAD -> Material.LEASH
    ItemTypes.NAME_TAG -> Material.NAME_TAG
    ItemTypes.COMMAND_BLOCK_MINECART -> Material.COMMAND_MINECART
    ItemTypes.MUTTON -> Material.MUTTON
    ItemTypes.COOKED_MUTTON -> Material.COOKED_MUTTON
    ItemTypes.BANNER -> Material.BANNER
    ItemTypes.END_CRYSTAL -> Material.END_CRYSTAL
    ItemTypes.SPRUCE_DOOR -> Material.SPRUCE_DOOR_ITEM
    ItemTypes.BIRCH_DOOR -> Material.BIRCH_DOOR_ITEM
    ItemTypes.JUNGLE_DOOR -> Material.JUNGLE_DOOR_ITEM
    ItemTypes.ACACIA_DOOR -> Material.ACACIA_DOOR_ITEM
    ItemTypes.DARK_OAK_DOOR -> Material.DARK_OAK_DOOR_ITEM
    ItemTypes.CHORUS_FRUIT -> Material.CHORUS_FRUIT
    ItemTypes.CHORUS_FRUIT_POPPED -> Material.CHORUS_FRUIT_POPPED
    ItemTypes.BEETROOT -> Material.BEETROOT
    ItemTypes.BEETROOT_SEEDS -> Material.BEETROOT_SEEDS
    ItemTypes.BEETROOT_SOUP -> Material.BEETROOT_SOUP
    ItemTypes.DRAGON_BREATH -> Material.DRAGONS_BREATH
    ItemTypes.SPLASH_POTION -> Material.SPLASH_POTION
    ItemTypes.SPECTRAL_ARROW -> Material.SPECTRAL_ARROW
    ItemTypes.TIPPED_ARROW -> Material.TIPPED_ARROW
    ItemTypes.LINGERING_POTION -> Material.LINGERING_POTION
    ItemTypes.SHIELD -> Material.SHIELD
    ItemTypes.ELYTRA -> Material.ELYTRA
    ItemTypes.SPRUCE_BOAT -> Material.BOAT_SPRUCE
    ItemTypes.BIRCH_BOAT -> Material.BOAT_BIRCH
    ItemTypes.JUNGLE_BOAT -> Material.BOAT_JUNGLE
    ItemTypes.ACACIA_BOAT -> Material.BOAT_ACACIA
    ItemTypes.DARK_OAK_BOAT -> Material.BOAT_DARK_OAK
    ItemTypes.TOTEM_OF_UNDYING -> Material.TOTEM
    ItemTypes.SHULKER_SHELL -> Material.SHULKER_SHELL
    ItemTypes.IRON_NUGGET -> Material.IRON_NUGGET
    ItemTypes.KNOWLEDGE_BOOK -> Material.KNOWLEDGE_BOOK
    ItemTypes.RECORD_13 -> Material.GOLD_RECORD
    ItemTypes.RECORD_CAT -> Material.GREEN_RECORD
    ItemTypes.RECORD_BLOCKS -> Material.RECORD_3
    ItemTypes.RECORD_CHIRP -> Material.RECORD_4
    ItemTypes.RECORD_FAR -> Material.RECORD_5
    ItemTypes.RECORD_MALL -> Material.RECORD_6
    ItemTypes.RECORD_MELLOHI -> Material.RECORD_7
    ItemTypes.RECORD_STAL -> Material.RECORD_8
    ItemTypes.RECORD_STRAD -> Material.RECORD_9
    ItemTypes.RECORD_WARD -> Material.RECORD_10
    ItemTypes.RECORD_11 -> Material.RECORD_11
    ItemTypes.RECORD_WAIT -> Material.RECORD_12
    else -> TODO("modded")
}

fun Material.toBlockType(): BlockType? = TODO()

fun BlockType.toMaterial(): Material = TODO()
